### ISSUE TITLE
KLA json

### ISSUE THREAD

**Issue by iandoug** [binarybottle/text_data#1]
Hi Arno

Can you please post the KLA json files ...

Thanks, Ian

**Comment by binarybottle** [comment]
Will do!

**Comment by binarybottle** [comment]
@iandoug -- I added all the layouts (from https://www.keyboard-design.com/internet-letter-layout-db.html) that I'm comparing with Engram in my article.

**Comment by iandoug** [comment]
FWIW, some layouts (eg Colemak) do better on KLATest if you switch the thumb to the other hand.

**Comment by iandoug** [comment]
Did you make beakl15.en.ansi.json ?
I didn't have it .... curious ...

**Comment by binarybottle** [comment]
Yes, I believe I did.

**Comment by iandoug** [comment]
I've removed most if not all "AltGr on ANSi" layouts from my collection for evaluation on grounds of being "bad for hands". Same with those Essie and Seelpy/CLP layouts as "bad for head"...

They'll stay in KLATest but won't be in updated version I'm busy with.

**Comment by binarybottle** [comment]
Woah -- I was unfamiliar with these layouts -- they look tricky to master!

It would be really good to clearly distinguish between ortho vs. diagonal layouts, as any layout in the latter benefit by ortho designs.
________________________________

**Comment by iandoug** [comment]
Please specify what you mean by ortho and diagonal ... 

Remember that Ergolinear / Matrix need lot look like that in real life.
Attached same shots Ergoliear and Matrix ... KLA does not  care about the angles of your hands, just the distances from one key to the next.

![kle-x6 4h-final-production-rev5](https://user-images.githubusercontent.com/12673886/113755827-0dff3780-9711-11eb-816b-e60fc94a675c.jpg)
![nirvana-0-8](https://user-images.githubusercontent.com/12673886/113755881-18213600-9711-11eb-9fea-278c1e39cab1.jpg)

**Comment by binarybottle** [comment]
Thanks -- I should be more specific.  Ortholinear as in orthogonal placement of keys with respect to each other, diagonal as in staggered keys.  The halves of a keyboard can of course be angled in 3-D with respect to each other, but this doesn't affect the relative positions of the keys within a divided portion of a keyboard.
________________________________

**Comment by iandoug** [comment]
>It would be really good to clearly distinguish between ortho vs. diagonal layouts, as any layout in the latter benefit by ortho designs.

I do, in the layout name ... 
name_etc.language.format
eg
qwerty.en.ansi
azerty.fr.iso
qwerty.en.ergodox 
etc

which assumes the reader is "skilled in the art" and knows the difference between ANSI, ISO and Ergodox (etc) layouts... :-)

Cheers ,Ian

**Comment by binarybottle** [comment]
Sorry -- I meant good to distinguish as in good to preselect/filter which designs results come back for when conducting a search in the database, or when comparing layouts in the KLA.
________________________________

**Comment by iandoug** [comment]
Den used naming scheme inherited from Patrick.
Version I am busy with uses my naming scheme, which is consistent between letter layout DB and KLA.

Let me do another complete reload, this time including Engram 2... it will have to run overnight, will send "provisional" report tomorrow. Thought I included it on last reload :-(

cheers, Ian

**Comment by iandoug** [comment]
Error with beakl15.en.ansi.json : beakl15.en.ansi, duplicate character on keyboard: ` (96) 
Error with beakl15.en.ansi.json : beakl15.en.ansi, duplicate character on keyboard: ~ (126) 
Error with beakl15.en.ansi.json : beakl15.en.ansi, characters not on keyboard: -

**Comment by binarybottle** [comment]
Great!  Looking forward!
________________________________

**Comment by binarybottle** [comment]
Thanks!   I left the upper left key alone, so there was a duplicate of ~ and ` characters.  I removed these, and added - above ; on the right, which was empty, rather than disturb the default keys on the left pinky.  Does this seem reasonable to you?

**Comment by iandoug** [comment]
I was going to do that, but decided to put minus on left as per matrix version ... I've included it in tonight's run but will remove afterwards. It scores well on the code input, but  using AltGr with thumb while typing (as opposed to the occasional Special Character) is not going to be hand-friendly. ANSI/ISO is already so human-unfriendly that we should not make it even worse :-)

If you want to compare Engram with others, pick other layouts that don't do special tricks. 
eg (if you want BEAKL)
https://www.keyboard-design.com/letterlayout.html?layout=beakl-opted4.en.ansi

This dates from Patrick / Den1 days so not optimised for KLATest but still rather good ... kinda weird how some of the things we did back then did not work so well on Den2 and Den3 but still score well on KLATest.

**Comment by binarybottle** [comment]
How confusing -- there are a gazillion different beakl layouts!  I don't even see the beakl-opted4 on the beakl site and it doesn't even resemble beakl-opted 3 (https://deskthority.net/wiki/BEAKL#BEAKL_Opted3).  I think I'll follow your lead and simply remove beakl from my comparison, so no layouts with "special tricks"!

**Comment by iandoug** [comment]
Yes, that's one of the criticisms levelled at the series ... little relation to each other.

The "commonality" is the search for Balanced Effort Advanced Keyboard Layout, hence BEAKL.

I've made multiple layouts, I tried to give them different names, but you tweak it here and tweak it there and pretty soon it looks very different ... so at what point does it get a new name?

Today's Toyota Corolla bears little resemblance to the 1980's version. (insert oblig Shakespeare rose quote)

**Comment by binarybottle** [comment]
My first, ill-fated car was a Toyota Corolla (the 'Olla, because the "Cor" fell off)!  I had many misadventures in that old rust bucket, and it cost me only $75!  It had one working door (the other was rusted shut) and no wipers.  I once drove in a blizzard with my left arm out the window to wipe away some of the snow!
